### PR TITLE
Nytproj - Main Development

### PR DESCRIPTION
**Pull request by bx44**
Final code for NYT Clone Project.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!
### Wow! The project looks really very good! The readme file is so descriptive! :+1:  

### But first of all let's fix the next problems and we can move on.
Kindly recommended checking HTML markup with this validator https://validator.w3.org/#validate_by_upload.

screenshot

Now it shows errors in your project

validator


#### Page structure

##### Navigation bar

* [x] It has a "Hamburger button", a search icon and a link with text on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)). Here needs to fix just "Humburger button" and include it in tag button.
* [x] It has the NY Times image logo embedded in the center
* [x] The NY Times logo is a link 
* [x] 'Log in' elements on the rightmost side 

##### Navigation bar

* [x] It should have a fixed position (it sticks to the top part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

##### Footer

* [x] It should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

* Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). 
* Pull Request should have a meaningful title and a short description [General requirements](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/).
 I hope in the next project you can do this! image


screen

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs corrections before it can be approved.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job implementing some of the changes requested duuring the last review :rocket: 
There is a bit more to do and you can merge :+1:. Please see some of the necessary changes below.

#### HTML Validations
Please run your HTML code by this validation tool and correct any errors it throws as regards your markup.

#### Use of floats
The major aim of this project is to help you get good at positioning using floats, that being said, you need to use that in positioning elements across the page. I noticed you used table to implement the section on 'The Theory of Inflation'. While there is nothing wrong with this approach :+1:, it deviates from the core of the excercise. Please see the requirement below.
screenshot

# Summary
You are almost done with this! :rocket:, just take a second look at the few things I listed above and you're good to go :smile: 

#### If you need some help, or you would like to bring anything to my attention or you just wanna chat, feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://oluwadamilareolusakin) :100:.

**Comment by bx44** [comment]
Hi, thanks for the review. We ran the ccode through the HTML Validator and the linter and it goes through without a problem. About the use of floats for the "Theory of Inflation" section, it would be unwise to use so much float to align this type of content, as its obviously in a grid layout such as a table. We did use float for aligning the layout of the page, the sidebars and in the header, where a float is actually a valid and reasonable option. Thanks a lot.

**Comment by shshamim63** [comment]
## Status :recycle: [!! Approved !!] :recycle: 
___
Hi @bx44  & @aecordova  :wave: ,
Great work on this project :clap: . I also agree with the previous reviewer that, you could place the items by using float. Cause the task of the project is actually :accept:  Positioning and Floating Elements :accept: . So the more you can use it, will be beneficial for you. So I am leaving it as optional to you.
___
### This :+1: is from me. You can merge it. And don't forget to fill the project completion form. 
___
## :herb:  Happy Coding :herb: 
### _Shakhawat Hossain_
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Pull request merged**
